### ISSUE TITLE
Issue with GUI scaling

### ISSUE THREAD

**Issue by 99Blocks** [Z-Doctor/SkillTree#5]
Sorry to bother you with another issue.

Updated to 1.1.0.2 today and it runs perfectly.

The only issue is that in any GUI scale other than AUTO, the font is covered and mis-aligned.

Took a screenshot in NORMAL scale. - https://i.gyazo.com/44eaf7913ef969bc0554c318ade3152b.png

Hope this isn't too much of a problem to fix.

**Comment by XZcutable** [comment]
Confirmed bug. Working on fix.

**Comment by XZcutable** [comment]
Fixed and verified. To be released
