### ISSUE TITLE
Create a Json system to add trees.

### ISSUE THREAD

**Issue by XZcutable** [Z-Doctor/SkillTree#8]
Planned functionality of skills created this way:

- Be able to position, have item icons and or custom background or png

- Have parents, use skill point requirements, use level requirement and check for items like skill do

- Be able to awards players items, points (perhaps run a command), attribute modifiers or potion effects

**Comment by MinecraftArchive** [comment]
How would u make a mod using JAVA to add onto this

**Comment by XZcutable** [comment]
Do you mean how would you use this mod to create a skill tree? Assuming you know how to make a Minecraft Mod you can use [this](../tree/Example) as an example. However, this is not the place for that kind of question.

**Comment by warriordark** [comment]
Why not have a similar setup to Better Questing? Im Sure Funwayguy would be glad to give insight on that end?
